### ISSUE TITLE
Could DTLN-aec process audio frame real-time on mobile?

### ISSUE THREAD

**Issue by DyncEric** [breizhn/DTLN-aec#3]
We have tested [DTLN](https://github.com/breizhn/DTLN), well done on mobile devices.  Great job 👍

**Comment by breizhn** [comment]
Thanks, nice to hear that people are testing it on mobile devices!

Yes it probably can. The model I handed in to the AEC-Challenge is relatively big (10M parameters) compared to the original DTLN model, but the structure is the same. If you were able to make the original DTLN run on a mobile device then it should not be that difficult to also make the DTLN-aec run. Maybe start testing with the small model (128 units) and work your way up to the big one (512 units).

**Comment by diepnghitinh** [comment]
I have just integrated to iOS using AudioUnit low latency. CPU reach to 40%, However, I will optimize performance it soon.. Thanks, @breizhn for your repository.
